spring:
  mvc:
    favicon:
      enabled: true

  security:
    user:
      password: password

    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "uri"
          client-id: "id"
          client-secret: "secrete"

    jwt:
      token:
#        secret-key: secret-key
#        expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds